image: golang:1.13.15

pipelines:
  branches:
    '*':
      - step:
          caches:
            - docker
          script:
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH}
            - make install-tools test build

    develop:
      - step:
          caches:
            - docker
          script:
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH}
            - docker login $REG_HOST --username $REG_USERNAME --password $REG_PASSWORD
            - DEV=true make install-tools test push

    master:
      - step:
          caches:
            - docker
          script:
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH}
            - docker login $REG_HOST --username $REG_USERNAME --password $REG_PASSWORD
            - PROD=true make install-tools test push

    'hotfix/*':
      - step:
          caches:
            - docker
          script:
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH}
            - docker login $REG_HOST --username $REG_USERNAME --password $REG_PASSWORD
            - HOTFIX=true make install-tools test push

options:
  docker: true
